### PR TITLE
🏗️ Use click for CLI

### PR DESCRIPTION
**Pull request by chaichontat**
Better comprehensibility for available commands.

image

### CODE REVIEW

**Comment by falexwolf** [comment]
I'll briefly cross-link some discussion on this! Not objecting, just want you to be aware of context.

**Comment by falexwolf** [comment]
First discussion: https://laminlabs.slack.com/archives/C04FPE8V01W/p1698673563715119

**Comment by falexwolf** [comment]
And two adjacent points:
- https://laminlabs.slack.com/archives/C03Q5TXF797/p1698665948875739
- https://laminlabs.slack.com/archives/C02M3LP41TL/p1700812209520409

**Comment by falexwolf** [comment]
Yeah, so, I like the new code a lot more! I don't like that we add a dependency, but I agree we needed auto-complete anyway and that's not achievable without a dependency.

It will break our CLI docs, though:

https://github.com/laminlabs/lamindb/blob/bf1c81e7ae8c177a7338d560521cc5b0c1cdc1aa/noxfile.py#L135-L164

So, I'm fine with it if you can fix the CLI docs. I looked through how Modal did it (they use Typer, which is based on Click).

**Comment by falexwolf** [comment]
Here is how they generate the CLI docs:

https://github.com/modal-labs/modal-client/blob/153a67f40282cc56f23ec38949ba8a3c3d7689b7/modal_docs/gen_cli_docs.py

**Comment by falexwolf** [comment]
To merge this into lamindb, you'll need a PR within lamindb and point to this submodule. The easiest is, of course, if you just recursively clone lamindb and then work within each submodule as if it was their own git repo. You then cd up to pull things together within lamindb.

**Review by falexwolf — APPROVED** [review]
Approved up to getting some sort of docs for the CLI back up and running. See comments!

**Comment by falexwolf** [comment]
Rebased on main!

**Comment by chaichontat** [comment]
Running `pytest` at `lamin login testuser1` results in 
`RuntimeError: Use your email for your first login in a compute environment. After that, you can use your handle.`.

**Comment by falexwolf** [comment]
This shouldn't occur because in the noxfile, these user accounts are set up.

https://github.com/laminlabs/lamindb/blob/e088ba3966a1ca482c4917af80a098ea268728f0/noxfile.py#L90-L91

Under the hood, this calls `lamin login testuser1@lamin.ai --key <API-key>`

**Comment by falexwolf** [comment]
I'll give you the key for testuser1! Then you can run things locally.

**Pull request merged**
